### ISSUE TITLE
Use Spacialist pref(s)

### ISSUE THREAD

**Issue by v1r0x** [eScienceCenter/ThesauRex#125]
https://github.com/eScienceCenter/Spacialist/issues/119 adds (user) preferences to Spacialist. At least the project name is also relevant in ThesauRex.

Additional ThesauRex settings:
- [x] Control if the toggle introduced with #127 should be set to visible or hide by default
- [x] If ThesauRex paired with Spacialist, there should be a link in the menu bar to go to the Spacialist instance (#120)

**Comment by dirkseidensticker** [comment]
The User-Prefs of ThesauRex should contain the following special entries:

- [ ] Control if the toggel introduced with #127 should be set to visible or hide by default
